### ISSUE TITLE
Build images for Vagrant

### ISSUE THREAD

**Issue by n-rodriguez** [netmanagers/salt-image-builder#6]
Hi there! It would be nice to have auto-generated Vagrant images to test with Kitchen Vagrant.

Some formulas are almost impossible to test with Docker (at least nfs and syslog-ng) so we should use Vagrant to test them. I've read that Vagrant don't work on Travis but works on Cirrus.

I'm working on a full Vagrant Kitchen file for [syslog-ng formula](https://github.com/n-rodriguez/syslog-ng-formula/tree/wip/kitchen)

cc @myii

**Comment by myii** [comment]
Thanks @n-rodriguez.  Just linking in a related issue and PR for the time being:

* https://github.com/saltstack-formulas/openssh-formula/issues/165
* https://github.com/saltstack-formulas/vault-formula/pull/32

**Comment by daks** [comment]
Packer is the way to go! :)

**Comment by n-rodriguez** [comment]
https://github.com/netmanagers/salt-image-builder#requirements

**Comment by n-rodriguez** [comment]
>  I've read that Vagrant don't work on Travis but works on Cirrus.

Well... it doesn't work on Cirrus... Cirrus provides VMs but doesn't seem to support nested virtualization :/

**Comment by myii** [comment]
@n-rodriguez They're responsive to e-mail contact (support+ci@cirruslabs.org, support@cirruslabs.org); that's how we eventually got it running with our Docker-based images.  The person I was in contact with responded on this long issue:

* https://github.com/saltstack-formulas/template-formula/issues/118

Might even be worth continuing the discussion there with `fkorotkov`.

In the meantime, I'm leaning towards a local solution of `.kitchen.yml` => `kitchen.vagrant.yml`, via. the `KITCHEN_YAML` or `KITCHEN_LOCAL_YAML` environment variable:

* https://github.com/saltstack-formulas/openssh-formula/pull/166#issue-316541412

---

Note: I used both e-mail address because the website displays one but links to the other: support@cirruslabs.org => support+ci@cirruslabs.org.
